project:
  type: website

website:
  title: "Lab Notes - Epistemic Moral Beliefs Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rameliaz/labnotes-emb
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css

editor: visual

