---
title: "Marlene Batzke's Talk on Agent-Based Modeling"
author: "Amelia Zein"
date: "2025-07-22"
categories: [learning]
---

# My notes from the talk

1.  ABM allows us to test theoretical assumptions on a micro (individual) and macro (group) level --- even the simplest assumptions can be super hard to predict.
2.  Allowing us to predict a system on a macro level as well as individual elements/roles on that macro level.
3.  Models don't need to be perfect, at least it serves the function (being useful).
4.  Start with very simple assumptions, therefore simple parameters. More parameters make models overfitting.
5.  People can basically refine the model parameters following up the simulation results and redo the simulations with updated parameters. But make sure to take notes on everything!
6.  We could do experiments to simulate the theories under different scenarios ---- Perfect for my epistemic moral beliefs project where I can simulate the predictions in a classroom setting!!!!
7.  Combining ABM with experiments data is perfectly possible, either use experimental results to create model parameters, or use simulation results to generate more hypotheses, making sense of conflicting experimental results.
8.  More parameters (assumptions) we put in the model would make the models unnecessarily complex. Start simple!
9.  In specifying the parameters we do and do not want to be super sure/specific about the accuracy or these parameters -- most importantly that we need to be sure that these assumptions can be tested. In this sense, we believe that the parameters we test theoretically vary in the population.
10. What defines a good model is actually **consistency** of the pattern that we'd like to predict. Don't expect we have clean indicators/indices to evaluate the models -- as in statistical models. Even statistical models we use regularly to test hypotheses are "true" under a ton of assumptions that we unconsciously ignore.

Example that she gave in the belief polarization project she is working on

- Coherence -- is defined as a fit with other beliefs depending on the belief system 
- Belief system -- is defined as correlation matrices of beliefs but needs to be subjective. To account for subjectivity, she used correlation class analysis (CCA)
- From a survey data (I think it was European Social Survey), she developed a three distinct profiles of belief systems (which correspond to three different CCA matrices), then she injected these three profiles into three types of agents.
- What happened next she measured diversity (of people within the same belief system group) and belief extremity (how deviate each belief system profile from the null - the moderates).
- She found that, when belief coherence is less important (vs. important), it is easier for people to reach consensus, which leads to less belief polarization.
